# Generated by Django 4.2 on 2024-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
