# Generated by Django 4.2 on 2024-12-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskManager', '0003_remove_task_due_date_remove_task_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
