# Generated by Django 4.2 on 2024-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskManager', '0004_remove_task_description_remove_task_is_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', '完了'), ('incomplete', '未完了'), ('pending', '保留')], default='incomplete', max_length=10),
        ),
    ]
