# Generated by Django 4.2 on 2025-05-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrnSurvey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField(null=True)),
                ('access_token', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TRN_SURVEY',
            },
        ),
        migrations.CreateModel(
            name='TrnSurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.trnsurvey')),
            ],
            options={
                'db_table': 'TRN_SURVEY_QUESTION',
            },
        ),
        migrations.CreateModel(
            name='TrnSurveyAnswer',
            fields=[
                ('responder', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1)),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.trnsurveyquestion')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.trnsurvey')),
            ],
            options={
                'db_table': 'TRN_SURVEY_ANSWER',
            },
        ),
    ]
