# Generated by Django 4.2 on 2025-05-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transurvey',
            name='access_token',
            field=models.CharField(default='test', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transurvey',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='TranSurveyQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.transurvey')),
            ],
            options={
                'db_table': 'TRN_SURVEY_QUESTION',
            },
        ),
    ]
