# Generated by Django 4.2 on 2025-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnsurveyanswer',
            name='answer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trnsurveyanswer',
            name='responder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='trnsurveyanswer',
            unique_together={('survey_id', 'question_id', 'responder')},
        ),
    ]
