# Generated by Django 4.2 on 2025-05-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0002_transurvey_access_token_alter_transurvey_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranSurvey',
            new_name='TrnSurvey',
        ),
        migrations.RenameModel(
            old_name='TranSurveyQuestion',
            new_name='TrnSurveyQuestion',
        ),
        migrations.CreateModel(
            name='TrnSurveyAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.trnsurveyquestion')),
                ('survey_id', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.CASCADE, to='EasySurvey.trnsurvey')),
            ],
            options={
                'db_table': 'TRN_SURVEY_ANSWER',
            },
        ),
    ]
