# Generated by Django 4.2 on 2025-05-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0002_trnsurveyanswer_answer_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trnsurveyanswer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='trnsurveyanswer',
            constraint=models.UniqueConstraint(fields=('survey_id', 'question_id', 'responder'), name='unique_survey_question_responder'),
        ),
    ]
