# Generated by Django 4.2 on 2025-05-10 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EasySurvey', '0003_alter_trnsurveyanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnsurvey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trnsurveyanswer',
            name='answer',
            field=models.CharField(choices=[(1, '〇'), (2, '△'), (3, '×')], max_length=1),
        ),
    ]
