# Generated by Django 4.2 on 2025-05-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0004_trnsurvey_created_by_alter_trnsurveyanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnsurveyquestion',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
