# Generated by Django 4.2 on 2025-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0005_alter_trnsurveyquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnsurvey',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
