# Generated by Django 4.2 on 2025-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasySurvey', '0006_alter_trnsurvey_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnsurveyquestion',
            name='show_choices_flag',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
    ]
